Repository bespoke-silicon-group/bsg_replicant, pull requests merged in 2024-12, with the labels that each got.

#851 move rodata to dmem
  examples/cuda/riscv.mk
Labels: Feature Request

#850 Deprecate num_vcache_rows_p in RTL
  hardware/hardware.mk
  libraries/platforms/common/dpi/hardware/dpi_top.sv
Labels: Bug

#848 SPMD Makefile Hot Fix
  examples/spmd/Makefile
  examples/spmd/bsg_attr_noalias_ex/Makefile
  examples/spmd/bsg_attr_noalias_remote_ex/Makefile
  examples/spmd/bsg_attr_remote_ex/Makefile
  examples/spmd/bsg_barrier_amoadd_test/Makefile
  examples/spmd/bsg_mcs_mutex_test/Makefile
  examples/spmd/bsg_set_tiles_x_y_asm/Makefile
  examples/spmd/bsg_simple_mutex_test/Makefile
  examples/spmd/credit_pkt_regfile_corrupt_test/Makefile
  examples/spmd/energy_lr_aq_test/Makefile
  examples/spmd/float_logf/Makefile
  examples/spmd/hw_barrier_16x8_interrupt_test/Makefile
  examples/spmd/hw_barrier_NxN_test/Makefile
  examples/spmd/hw_barrier_context_switch_test/Makefile
  examples/spmd/hw_barrier_csr_test/Makefile
  examples/spmd/hw_barrier_reconfigure_test/Makefile
  examples/spmd/icache_miss_bombing/Makefile
  examples/spmd/icache_miss_double_loop_test/Makefile
  examples/spmd/interrupt_handler_asm_example/Makefile
  examples/spmd/memtest2022/Makefile
  examples/spmd/pc_profiler/Makefile
  examples/spmd/stall_remote_ld_wb/Makefile
  examples/spmd/strider/Makefile
Labels: Bug

#840 Move bsg_manycore_regression_platform.h to platform directory, Makefile includes and flags cleanup, Verilator fixes
  examples/.gitignore
  examples/execution.mk
  libraries/README.md
  libraries/libraries.mk
  libraries/platforms/bigblade-vcs/compilation.mk
  libraries/platforms/bigblade-vcs/library.mk
  libraries/platforms/bigblade-verilator/bsg_manycore_regression_platform.c
  libraries/platforms/bigblade-verilator/compilation.mk
  libraries/platforms/bigblade-verilator/execution.mk
  libraries/platforms/bigblade-verilator/link.mk
  libraries/platforms/bigblade-xcelium/bsg_manycore_platform.cpp
  libraries/platforms/bigblade-xcelium/library.mk
  libraries/platforms/common/dpi/compilation.mk
  libraries/platforms/common/dpi/library.mk
  libraries/platforms/common/dpi/library/bsg_manycore_platform.cpp
  libraries/platforms/common/dpi/library/bsg_manycore_regression_platform.h
Labels: Feature Request

#839 Enable DRAM Support
  hardware/hardware.mk
  libraries/bsg_manycore_config.cpp
  libraries/bsg_manycore_config.h
  libraries/bsg_manycore_config_id_to_string.c
  libraries/bsg_manycore_config_pod.h
  libraries/bsg_manycore_loader.cpp
  machines/README.md
  machines/bigblade_pod_X1Y1_ruche_X16Y8_hbm/Makefile.machine.include
  machines/pod_X1Y1_mesh_X2Y2_hbm_one_pseudo_channel/Makefile.machine.include
  machines/pod_X1Y1_ruche_X16Y16_hbm_one_pseudo_channel/Makefile.machine.include
  machines/pod_X1Y1_ruche_X16Y8_hbm/Makefile.machine.include
  machines/pod_X1Y1_ruche_X16Y8_hbm_one_pseudo_channel/Makefile.machine.include
  machines/pod_X1Y1_ruche_X32Y16_hbm_one_pseudo_channel/Makefile.machine.include
  machines/pod_X1Y1_ruche_X32Y8_hbm_one_pseudo_channel/Makefile.machine.include
  machines/pod_X1Y1_ruche_X4Y2_hbm_one_pseudo_channel/Makefile.machine.include
  machines/pod_X1Y1_ruche_X4Y4_hbm_one_pseudo_channel/Makefile.machine.include
  machines/pod_X1Y1_ruche_X8Y4_hbm/Makefile.machine.include
  machines/pod_X1Y1_ruche_X8Y4_hbm_one_pseudo_channel/Makefile.machine.include
  machines/pod_X1Y1_ruche_X8Y8_hbm_one_pseudo_channel/Makefile.machine.include
  machines/pod_X2Y2_ruche_X16Y8_hbm/Makefile.machine.include
  machines/pod_X4Y4_ruche_X16Y8_hbm/Makefile.machine.include
Labels: WIP

#842 SPMD Loader Add Flags for FPGA Tests
  examples/spmd/.gitignore
  examples/spmd/Makefile
  examples/spmd/loader.c
  examples/spmd/loader.mk
  examples/spmd/test_saif/Makefile
Labels: Feature Request

#857 VCS Platform CADENV Optimizations
  cadenv.mk
  libraries/platforms/bigblade-vcs/execution.mk
  libraries/platforms/bigblade-vcs/link.mk
  platform.mk
Labels: Enhancement

#841 Bigblade-FPGA Machine and Platform
  libraries/platforms/bigblade-fpga/bsg_manycore_mmio.cpp
  libraries/platforms/bigblade-fpga/bsg_manycore_mmio.h
  libraries/platforms/bigblade-fpga/bsg_manycore_platform.cpp
  libraries/platforms/bigblade-fpga/bsg_manycore_regression_platform.h
  libraries/platforms/bigblade-fpga/compilation.mk
  libraries/platforms/bigblade-fpga/execution.mk
  libraries/platforms/bigblade-fpga/hardware.mk
  libraries/platforms/bigblade-fpga/library.mk
  libraries/platforms/bigblade-fpga/link.mk
  machines/bigblade_pod_X4Y2_ruche_X16Y8_fpga/Makefile.machine.include
  machines/bigblade_pod_X4Y4_ruche_X16Y8_fpga/Makefile.machine.include
  machines/bigblade_pod_X4Y4_ruche_X16Y8_fpga_top_dram_enable/Makefile.machine.include
Labels: Feature Request

#845 Add HB_MC SPMD Test Series
  examples/spmd/Makefile
  examples/spmd/hb_mc_00_local_dmem/Makefile
  examples/spmd/hb_mc_01_vcache_dram/Makefile
  examples/spmd/hb_mc_02_noc_intrapod/Makefile
  examples/spmd/hb_mc_03_icache/Makefile
  examples/spmd/hb_mc_04_noc_interpod/Makefile
  examples/spmd/hb_mc_05_regfile/Makefile
  examples/spmd/hb_mc_06_icache_miss/Makefile
  examples/spmd/hb_mc_07_vcache_dram_prbs/Makefile
  examples/spmd/hb_mc_08_power_burning/Makefile
  examples/spmd/hb_mc_09_power_high_freq/Makefile
  examples/spmd/hb_mc_10_sdr_init_full/Makefile
  examples/spmd/hb_mc_11_sdr_init_half/Makefile
  examples/spmd/hb_mc_12_sdr_prbs_half/Makefile
  examples/spmd/loader.mk
Labels: Feature Request
